# Generated by Django 5.0 on 2024-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profilepicture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
